[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
common = { path = "../common" }
log = "0.4"
tokio = { version = "1.41.0", features = ["full"] }
env_logger = "0.11.5"
ffmpeg-sidecar = "1.2.0"
bincode = "1.3.3"
