[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
common = { path = "../common" }
log = "0.4.22"
serde = "1.0.210"
tokio = { version = "1.40.0", features = ["full"] }
env_logger = "0.11.5"
